# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee90d3ae9657a6aed970cbe4cd94e25dfbdc5f268b53306f50d35801cee90b3c836d6877c3eb59c1590e2555a6dfd313afbc9cf2b1dff123b0e19e703d76e28

  smtp_settings:
    address:              mailtrap.io
    port:                 2525
    domain:               mailtrap.io
    user_name:            435547c8a03ac8a8a
    password:             840009c439dfdd
    authentication:       cram_md5
    enable_starttls_auto: true
  default_url_options:
    host: localhost:4000
  default_options:
    from: nonreply@qishicpc.com
  default_confirmation_callback: http://localhost:3000

test:
  secret_key_base: 14a977e8e3e4568f0646a950953408f68f4bbca2640e44b72b47934177c6246656cde7a6f96255aa97f247be4bbc7a8da440488126ff41a0b0edc46453022080

  smtp_settings:
    address:              mailtrap.io
    port:                 2525
    domain:               mailtrap.io
    user_name:            435547c8a03ac8a8a
    password:             840009c439dfdd
    authentication:       cram_md5
    enable_starttls_auto: true
  default_url_options:
    host: localhost:4000
  default_options:
    from: nonreply@qishicpc.com
  default_confirmation_callback: http://localhost:3000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  smtp_settings:
      address:              <%= ENV["SMTP_ADDRESS"] %>
      port:                 <%= ENV["SMTP_PORT"] %>
      domain:               <%= ENV["SMTP_DOMAIN"] %>
      user_name:            <%= ENV["SMTP_USERNAME"] %>
      password:             <%= ENV["SMTP_PASSWORD"] %>
      authentication:       <%= ENV["SMTP_AUTHENTICATION"] %>
      enable_starttls_auto: <%= ENV["SMTP_TLS"] %>
  default_url_options:
    host: <%= ENV["BACK_END_URL"] %>
  default_options:
    from: <%= ENV["MAIL_FROM"] %>
  default_confirmation_callback: <%= ENV["CONFIRMATION_CALLBACK"] %>
